apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "github-provider.fullname" . }}
  labels:
    {{- include "github-provider.labels" . | nindent 4 }}
data:
  GITHUB_PROVIDER_DEBUG: "{{ .Values.env.GITHUB_PROVIDER_DEBUG }}"
  GITHUB_PROVIDER_POLL_INTERVAL: "{{ .Values.env.GITHUB_PROVIDER_POLL_INTERVAL }}"
